// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6_2J4boeXo-gWZLDjlysIu76vi26s4Lg',
    appId: '1:75741263253:web:0cf98e9fcff2e00c3a729c',
    messagingSenderId: '75741263253',
    projectId: 'tabarno-firebase-finals',
    authDomain: 'tabarno-firebase-finals.firebaseapp.com',
    storageBucket: 'tabarno-firebase-finals.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjROEbKAYLEStyBVvNWh6FJ2cHKMLS-Iw',
    appId: '1:75741263253:android:38bf74473dea70a43a729c',
    messagingSenderId: '75741263253',
    projectId: 'tabarno-firebase-finals',
    storageBucket: 'tabarno-firebase-finals.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_TWWISWkcdCbPT-zq8kXpYaEO_zlPd7U',
    appId: '1:75741263253:ios:45a902f0240aaeae3a729c',
    messagingSenderId: '75741263253',
    projectId: 'tabarno-firebase-finals',
    storageBucket: 'tabarno-firebase-finals.appspot.com',
    iosBundleId: 'com.example.mad3FinalsubmissionTabarno',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_TWWISWkcdCbPT-zq8kXpYaEO_zlPd7U',
    appId: '1:75741263253:ios:45a902f0240aaeae3a729c',
    messagingSenderId: '75741263253',
    projectId: 'tabarno-firebase-finals',
    storageBucket: 'tabarno-firebase-finals.appspot.com',
    iosBundleId: 'com.example.mad3FinalsubmissionTabarno',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6_2J4boeXo-gWZLDjlysIu76vi26s4Lg',
    appId: '1:75741263253:web:f7b5eab1c8a1b5753a729c',
    messagingSenderId: '75741263253',
    projectId: 'tabarno-firebase-finals',
    authDomain: 'tabarno-firebase-finals.firebaseapp.com',
    storageBucket: 'tabarno-firebase-finals.appspot.com',
  );
}
